### ISSUE TITLE
Sandbox - Something went wrong

### ISSUE THREAD

**Issue by obycode** [hirosystems/explorer#1053]
**Describe the bug**
Trying to interact with a contract in the sandbox gives me the "Something went wrong" error page.

https://explorer.stacks.co/sandbox/contract-call/SPXVRSEH2BKSXAEJ00F1BY562P45D5ERPSKR4Q33.xverse-pool-v2/delegate-stx?chain=mainnet

**To Reproduce**
1. Go to https://explorer.stacks.co/sandbox/contract-call/SPXVRSEH2BKSXAEJ00F1BY562P45D5ERPSKR4Q33.xverse-pool-v2/delegate-stx?chain=mainnet
2. See error

**Expected behavior**
This page should load the interface for making a contract call.

**Desktop (please complete the following information):**
 - OS: MacOS 12.6.3
 - Browser: Chrome
 - Version: 111.0

**Additional context**
I see this in the console:

```
instrument.js:108 TypeError: Cannot read properties of undefined (reading '0')
    at TupleArgumentInput.tsx:40:47
    at Array.map (<anonymous>)
    at C (TupleArgumentInput.tsx:23:16)
    at ab (react-dom.production.min.js:167:135)
    at i (react-dom.production.min.js:290:335)
    at oO (react-dom.production.min.js:280:383)
    at react-dom.production.min.js:280:319
    at oF (react-dom.production.min.js:280:319)
    at ox (react-dom.production.min.js:271:86)
    at oS (react-dom.production.min.js:268:399)
    at x (scheduler.production.min.js:13:197)
    at MessagePort.T (scheduler.production.min.js:14:126)
```

**Comment by obycode** [comment]
Th problem seems to be resolved in the current release. Thanks!
