### ISSUE TITLE
Clarinet devnet: Stacks explorer fails with REDIS_URL is not defined

### ISSUE THREAD

**Issue by mijoco-btc** [hirosystems/explorer#1698]
**Stacks Explorer Docker Container Failure**

**To Reproduce**

1. clarinet devnet start
2. wait for containers to run (all go green)
3. goto http://localhost:8000/?chain=testnet&api=http://localhost:3999
4. "Something went wrong"

**Expected behavior**
Stacks explorer to load. Note: it has been running fine on same machine - this error turned up between Mon 24th and Thur 27th June. 

**Screenshots**
<img width="536" alt="Screenshot 2024-06-27 at 10 45 05" src="https://github.com/hirosystems/clarinet/assets/4384929/4d0daca8-3f21-47c7-ba7c-b7f459a3accc">
<img width="1272" alt="Screenshot 2024-06-27 at 10 44 57" src="https://github.com/hirosystems/clarinet/assets/4384929/b1f2cf69-cfb4-4f84-a366-6ef6bec12b8b">

**Environment (please complete the following information):**
 - OS (version): [e.g. macOS Monterey (12.6.1)]
 - Docker version 26.1.4, build 5650f9b
 - Clarinet 2.6.0

**Additional context**

**docker logs -f stacks-explorer.bitcoin-dao.devnet**

```
$ docker logs -f stacks-explorer.bitcoin-dao.devnet
   ▲ Next.js 14.1.4
   - Local:        http://8ae58ff959c1:3000
   - Network:      http://172.18.0.8:3000

 ✓ Ready in 129ms
[debug] REDIS_URL is not defined
[debug] token price - cache miss
[debug] REDIS_URL is not defined
TypeError: Failed to parse URL from
    at new Request (node:internal/deps/undici/undici:6110:19)
    at i (/app/node_modules/.pnpm/next@14.1.4_@babel+core@7.23.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:177204)
    ... 3 lines matching cause stack trace ...
    at async _ (/app/.next/server/chunks/87.js:102:45056) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:405:5)
      at new URL (node:internal/url:676:13)
      at new Request (node:internal/deps/undici/undici:6108:25)
      at i (/app/node_modules/.pnpm/next@14.1.4_@babel+core@7.23.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:177204)
      at F (/app/.next/server/chunks/937.js:1:39749)
      at /app/.next/server/chunks/937.js:1:41898
      at async globalThis.fetch (/app/.next/server/chunks/937.js:1:36493)
      at async _ (/app/.next/server/chunks/87.js:102:45056) {
    input: '',
    code: 'ERR_INVALID_URL'
  }
}
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '3481489950'
}
[debug] REDIS_URL is not defined
[debug] token price - cache miss
[debug] REDIS_URL is not defined
TypeError: Failed to parse URL from
    at new Request (node:internal/deps/undici/undici:6110:19)
    at i (/app/node_modules/.pnpm/next@14.1.4_@babel+core@7.23.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:177204)
    ... 3 lines matching cause stack trace ...
    at async _ (/app/.next/server/chunks/87.js:102:45056) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:405:5)
      at new URL (node:internal/url:676:13)
      at new Request (node:internal/deps/undici/undici:6108:25)
      at i (/app/node_modules/.pnpm/next@14.1.4_@babel+core@7.23.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:177204)
      at F (/app/.next/server/chunks/937.js:1:39749)
      at /app/.next/server/chunks/937.js:1:41898
      at async globalThis.fetch (/app/.next/server/chunks/937.js:1:36493)
      at async _ (/app/.next/server/chunks/87.js:102:45056) {
    input: '',
    code: 'ERR_INVALID_URL'
  }
}
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '3481489950'
}
```

**Comment by radicleart** [comment]
This is an odd issue - given explorer with 2.6.0 clarinet was working a few days.

I imagine its related to this old mac i'm using while my machine is being fixed.

Just wanted to let you know for info !

**Comment by radicleart** [comment]
This works.

```stacks_explorer_image_url = "hirosystems/explorer:1.185.3"```

something nasty since then?
