### ISSUE TITLE
Explorer should build without Sentry credentials defined

### ISSUE THREAD

**Issue by gzelda** [hirosystems/explorer#562]
**Describe the bug**

`$ yarn build`

```
Failed to compile.

Sentry CLI Plugin: Command failed: /Users/gavin/Desktop/explorer/node_modules/@sentry/cli/sentry-cli releases new minLwZ8lAAQbuphsDxNBG
error: API request failed
  caused by: sentry reported an error: Authentication credentials were not provided. (http status: 401)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.


> Build error occurred
Error: > Build failed because of webpack errors
    at /Users/gavin/Desktop/explorer/node_modules/next/dist/build/index.js:397:19
    at async Span.traceAsyncFn (/Users/gavin/Desktop/explorer/node_modules/next/dist/telemetry/trace/trace.js:60:20)
    at async Object.build [as default] (/Users/gavin/Desktop/explorer/node_modules/next/dist/build/index.js:77:25)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by fbwoolf** [comment]
Trying to reproduce this, but even if I delete my env variables and the local auth token it still builds for me? 🤔
