### ISSUE TITLE
Error thrown when tx has been pending for long time 

### ISSUE THREAD

**Issue by Eshwari007** [hirosystems/explorer#650]
Tested the issue on Prod version 3.1.1

**Steps to reproduce:**

- User sends an STX and non STX tx with very low fees such as 0.000333 (another use case would be with selecting low fee from custom fee dropdown)
- User notices that the tx is in Pending mode in Activity list
- User selects  the tx and brought to explorer page
- Navigate away from explorer and notices that the tx has been Pending for quite some time
- Move to other tabs and upon return received the below error:

<img width="1409" alt="Screen Shot 2022-02-16 at 12 16 16 PM" src="https://user-images.githubusercontent.com/38872890/154321572-75ef4b99-3edf-4a08-8554-f7970863f2e9.png">

URL: https://explorer.stacks.co/txid/0x74e327238a7ca1d8f90df6f38d60116d2dc3166f33b9b0e5a5dde155bf70c040?chain=mainnet

**Comment by Eshwari007** [comment]
This was also able to be reproduced on testnet  v3.2.0-beta.8, URL :.https://explorer.stacks.co/txid/0x42cd220412feb194eabcfcc2f5db0c5a1dbc42ccac3a135159816bbac99b2387?chain=testnet

**Comment by Eshwari007** [comment]
The issue was reproduced on refs/pull/2281/merge- White Buffalo release version as well
<img width="1246" alt="Screen Shot 2022-03-02 at 3 06 14 PM" src="https://user-images.githubusercontent.com/38872890/156441580-c70fdf22-af80-40aa-9d08-4ab03dbf72ac.png">
<img width="1408" alt="Screen Shot 2022-03-02 at 3 07 47 PM" src="https://user-images.githubusercontent.com/38872890/156441582-cb64575b-cf46-4ea1-9c12-ba167a0d0670.png">

**Comment by Eshwari007** [comment]
> The issue was reproduced on refs/pull/2281/merge- White Buffalo release version as well <img alt="Screen Shot 2022-03-02 at 3 06 14 PM" width="1246" src="https://user-images.githubusercontent.com/38872890/156441580-c70fdf22-af80-40aa-9d08-4ab03dbf72ac.png"> <img alt="Screen Shot 2022-03-02 at 3 07 47 PM" width="1408" src="https://user-images.githubusercontent.com/38872890/156441582-cb64575b-cf46-4ea1-9c12-ba167a0d0670.png">

The issue this time however was not for a tx which was pending for a long time.
 The explorer tab was left aside for a couple of extra mins upon successful tx and when the user attempted to select the explorer tab again ,the error was visible on explorer.

**Comment by diwakergupta** [comment]
@andresgalante @He1DAr any update on this? It's a very common scenario (you just broadcast a txn, so naturally you open it up in the Explorer and wait for it to confirm) and makes for a pretty bad UX. IMO this should be pretty high priority to fix.

**Comment by andresgalante** [comment]
@diwakergupta you are right, the experience is bad.

@markmhx I have 2 ideas here: Heidar is focusing now on the Desktop wallet, maybe he can pick this one up before working on the state refactor, after working on the explorer search. The other option is for Fara to pick this up as she finished with the Ledger transaction flow. What do you think?

**Comment by Eshwari007** [comment]
@He1DAr  I was able to reproduce the issue:https://explorer.stacks.co/txid/0x1aec36806bf3dd107aaf16248449115e6ab9bfc23cfc1f6a67b6c412bd06500e?chain=mainnet

**Comment by whoabuddy** [comment]
I can confirm this error still happens for me, but under a slightly different scenario.

I can leave the explorer tab open with a pending tx or a tx in a microblock and all works as expected, even after long periods of time.

When the tx moves into an anchor block, though, this screen is generated when the tab is opened again. If I refresh the page, then I see the completed tx.

I thought there was an older issue on this topic but I'm having trouble finding it. Wanted to add my comments here as well as from `@shovelandsandbox#4979` in the `#explorer` discord channel just now, who's experiencing the same problem:
https://discord.com/channels/621759717756370964/911531946738339900/954392239734411335

**Comment by whoabuddy** [comment]
Found the original issue here: https://github.com/hirosystems/explorer/issues/518

My experience is the same in that it crashes when going from pending/microblock -> anchored, but the screens I see now match the application error above. I didn't realize this issue was closed out or I would've filed a new one sooner, but maybe there is some context there that could be helpful!

**Comment by whoabuddy** [comment]
Was able to replicate again and can confirm it's when the tx goes from microblock -> anchored. Console logs below!

```
instrument.js:109 Error: Vt suspended while rendering, but no fallback UI was specified.

Add a <Suspense fallback=...> component higher in the tree to provide a loading indicator or placeholder to display.
    at Si (react-dom.production.min.js:248:253)
    at xi (react-dom.production.min.js:250:158)
    at vi (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Wl (react-dom.production.min.js:122:325)
    at Ql (react-dom.production.min.js:123:61)
    at Hl (react-dom.production.min.js:122:428)
    at fi (react-dom.production.min.js:237:203)
    at No (react-dom.production.min.js:170:408)
    at index.js:416:66
    at Set.forEach (<anonymous>)
    at index.js:416:44
    at Array.forEach (<anonymous>)
    at E (index.js:406:13)
    at index.js:295:9
    at Object.r.write (index.js:555:7)
    at k (index.js:301:32)
    at O (index.js:313:27)
    at t (index.js:336:35)
    at l (query.js:48:9)
    at queryObserver.js:485:11
    at Array.forEach (<anonymous>)
    at queryObserver.js:484:26
    at e.t.batch (notifyManager.js:22:18)
    at t.n.notify (queryObserver.js:472:5)
    at t.n.updateResult (queryObserver.js:432:10)
    at t.n.onQueryUpdate (queryObserver.js:462:10)
    at query.js:356:18
    at Array.forEach (<anonymous>)
    at query.js:355:24
    at e.t.batch (notifyManager.js:22:18)
    at e.t.dispatch (query.js:354:5)
    at e.t.setData (query.js:73:10)
    at Object.onSuccess (query.js:298:16)
    at p (retryer.js:53:50)

instrument.js:109 Error: Vt suspended while rendering, but no fallback UI was specified.

Add a <Suspense fallback=...> component higher in the tree to provide a loading indicator or placeholder to display.
    at Si (react-dom.production.min.js:248:253)
    at xi (react-dom.production.min.js:250:158)
    at vi (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Wl (react-dom.production.min.js:122:325)
    at Ql (react-dom.production.min.js:123:61)
    at Hl (react-dom.production.min.js:122:428)
    at fi (react-dom.production.min.js:237:203)
    at No (react-dom.production.min.js:170:408)
    at index.js:416:66
    at Set.forEach (<anonymous>)
    at index.js:416:44
    at Array.forEach (<anonymous>)
    at E (index.js:406:13)
    at index.js:295:9
    at Object.r.write (index.js:555:7)
    at k (index.js:301:32)
    at O (index.js:313:27)
    at t (index.js:336:35)
    at l (query.js:48:9)
    at queryObserver.js:485:11
    at Array.forEach (<anonymous>)
    at queryObserver.js:484:26
    at e.t.batch (notifyManager.js:22:18)
    at t.n.notify (queryObserver.js:472:5)
    at t.n.updateResult (queryObserver.js:432:10)
    at t.n.onQueryUpdate (queryObserver.js:462:10)
    at query.js:356:18
    at Array.forEach (<anonymous>)
    at query.js:355:24
    at e.t.batch (notifyManager.js:22:18)
    at e.t.dispatch (query.js:354:5)
    at e.t.setData (query.js:73:10)
    at Object.onSuccess (query.js:298:16)
    at p (retryer.js:53:50)

instrument.js:109 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```

**Comment by Eshwari007** [comment]
@fbwoolf This should be live in Explorer now, correct?

**Comment by Eshwari007** [comment]
Tested the issue with a STX tx,was not able to reproduce it.
WIl keep an eye on etc tx as well
https://explorer.stacks.co/txid/0x2a35ed4dd63153339023a585f340d5bdf8f12a18e88794bb3a8bc797b43baff1?chain=mainnet
