### ISSUE TITLE
Application error/exception when trying to view Holdings -> Collectibles on contract/txid page

### ISSUE THREAD

**Issue by 0xbabo** [hirosystems/explorer#952]
When viewing a contract at the /txid/ endpoint, an exception occurs after pressing Holdings -> Collectibles if the contract is holding NFT assets. The exception does not occur at the /address/ endpoint or if it is not holding NFT assets. 

> Application error: a client-side exception has occurred (see the browser console for more information).

Exception (/txid/ with NFT): 
https://explorer.stacks.co/txid/SPNWZ5V2TPWGQGVDR6T7B6RQ4XMGZ4PXTEE0VQ0S.marketplace-v4?chain=mainnet
https://explorer.stacks.co/txid/SP1BX0P4MZ5A3A5JCH0E10YNS170QFR2VQ6TT4NRH.byzantion-market-v7?chain=mainnet
Works (/address/ with NFT): 
https://explorer.stacks.co/address/SPNWZ5V2TPWGQGVDR6T7B6RQ4XMGZ4PXTEE0VQ0S.marketplace-v4?chain=mainnet
https://explorer.stacks.co/address/SP1BX0P4MZ5A3A5JCH0E10YNS170QFR2VQ6TT4NRH.byzantion-market-v7?chain=mainnet
Works (/txid/ w/o NFT: 
https://explorer.stacks.co/txid/SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.alex-vault?chain=mainnet
Works (/address/ w/o NFT): 
https://explorer.stacks.co/address/SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.alex-vault?chain=mainnet

Contracts are typically viewed from the /txid/ endpoint so it should be expected to work there.

**Comment by 0xBabo** [comment]
Console log error from https://explorer.stacks.co/txid/SP1BX0P4MZ5A3A5JCH0E10YNS170QFR2VQ6TT4NRH.byzantion-market-v7?chain=mainnet
```
TypeError: Cannot read properties of undefined (reading 'SP125J1ADVYWGWB9NQRCVGKYAG73R17ZNMV17XEJ7.mutant-monkeys::mutant-monkeys')
    at principal-token-balances.tsx:31:13
    at Array.map (<anonymous>)
    at T (principal-token-balances.tsx:24:50)
    at oo (react-dom.production.min.js:157:137)
    at Ku (react-dom.production.min.js:267:460)
    at Li (react-dom.production.min.js:250:347)
    at Ni (react-dom.production.min.js:250:278)
    at Pi (react-dom.production.min.js:250:138)
    at bi (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ql (react-dom.production.min.js:122:325)
    at Yl (react-dom.production.min.js:123:61)
    at Kl (react-dom.production.min.js:122:428)
    at Me (react-dom.production.min.js:292:101)
    at Xt (react-dom.production.min.js:73:352)
    at HTMLDivElement.i (helpers.js:73:23)
(anonymous) @ instrument.js:109
```

**Comment by andresgalante** [comment]
Thanks for the report. We already have an issue related to it, I'll close this one in favor of https://github.com/hirosystems/explorer/issues/941
